package hooks

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// HookType represents a git hook type
type HookType string

const (
	HookPreCommit        HookType = "pre-commit"
	HookPrePush          HookType = "pre-push"
	HookCommitMsg        HookType = "commit-msg"
	HookPrepareCommitMsg HookType = "prepare-commit-msg"
)

// GitHook represents a git hook configuration
type GitHook struct {
	Type    HookType
	Script  string
	Enabled bool
}

// Manager manages git hooks for the project
type Manager struct {
	repoPath string
	hooksDir string
	dryRun   bool
}

// NewManager creates a new git hooks manager
func NewManager(repoPath string, dryRun bool) *Manager {
	hooksDir := filepath.Join(repoPath, ".git", "hooks")
	return &Manager{
		repoPath: repoPath,
		hooksDir: hooksDir,
		dryRun:   dryRun,
	}
}

// IsGitRepo checks if the path is a git repository
func (m *Manager) IsGitRepo() bool {
	gitDir := filepath.Join(m.repoPath, ".git")
	info, err := os.Stat(gitDir)
	if err != nil {
		return false
	}
	return info.IsDir()
}

// Install installs git hooks for the project
func (m *Manager) Install() error {
	if !m.IsGitRepo() {
		return fmt.Errorf("not a git repository: %s", m.repoPath)
	}

	// Ensure hooks directory exists
	if err := os.MkdirAll(m.hooksDir, 0755); err != nil {
		return fmt.Errorf("failed to create hooks directory: %w", err)
	}

	// Define hooks to install
	hooks := []GitHook{
		{
			Type:   HookPreCommit,
			Script: m.generatePreCommitScript(),
		},
		{
			Type:   HookPrePush,
			Script: m.generatePrePushScript(),
		},
	}

	for _, hook := range hooks {
		if err := m.installHook(hook); err != nil {
			return fmt.Errorf("failed to install %s hook: %w", hook.Type, err)
		}
	}

	return nil
}

// Uninstall removes installed git hooks
func (m *Manager) Uninstall() error {
	if !m.IsGitRepo() {
		return fmt.Errorf("not a git repository: %s", m.repoPath)
	}

	hooks := []HookType{HookPreCommit, HookPrePush, HookCommitMsg, HookPrepareCommitMsg}

	for _, hookType := range hooks {
		hookPath := filepath.Join(m.hooksDir, string(hookType))
		if _, err := os.Stat(hookPath); err == nil {
			if m.dryRun {
				fmt.Printf("[DRY-RUN] Would remove %s\n", hookPath)
			} else {
				if err := os.Remove(hookPath); err != nil {
					return fmt.Errorf("failed to remove %s: %w", hookPath, err)
				}
			}
		}
	}

	return nil
}

// Status shows the status of installed hooks
func (m *Manager) Status() ([]GitHook, error) {
	if !m.IsGitRepo() {
		return nil, fmt.Errorf("not a git repository: %s", m.repoPath)
	}

	var hooks []GitHook

	hookTypes := []HookType{HookPreCommit, HookPrePush, HookCommitMsg, HookPrepareCommitMsg}

	for _, hookType := range hookTypes {
		hookPath := filepath.Join(m.hooksDir, string(hookType))
		hook := GitHook{
			Type: hookType,
		}

		if info, err := os.Stat(hookPath); err == nil {
			hook.Enabled = true
			// Read script content
			content, err := os.ReadFile(hookPath)
			if err == nil {
				hook.Script = string(content)
			}
			// Check if executable
			if info.Mode()&0111 == 0 {
				hook.Enabled = false
			}
		}

		hooks = append(hooks, hook)
	}

	return hooks, nil
}

func (m *Manager) installHook(hook GitHook) error {
	hookPath := filepath.Join(m.hooksDir, string(hook.Type))

	if m.dryRun {
		fmt.Printf("[DRY-RUN] Would install %s hook at %s\n", hook.Type, hookPath)
		return nil
	}

	// Write hook script
	if err := os.WriteFile(hookPath, []byte(hook.Script), 0755); err != nil {
		return fmt.Errorf("failed to write hook file: %w", err)
	}

	return nil
}

func (m *Manager) generatePreCommitScript() string {
	return `#!/bin/bash
# debian-composer pre-commit hook
# Generated by debian-composer-go

set -e

echo "Running pre-commit checks..."

# Check for Go formatting
if command -v gofmt &> /dev/null; then
    UNFORMATTED=$(gofmt -l .)
    if [ -n "$UNFORMATTED" ]; then
        echo "Error: The following files are not formatted:"
        echo "$UNFORMATTED"
        echo ""
        echo "Run 'gofmt -w .' to fix formatting"
        exit 1
    fi
fi

# Run go vet
if command -v go &> /dev/null; then
    go vet ./...
fi

# Run tests
if command -v go &> /dev/null && [ -f "go.mod" ]; then
    go test ./... -short
fi

echo "Pre-commit checks passed!"
`
}

func (m *Manager) generatePrePushScript() string {
	return `#!/bin/bash
# debian-composer pre-push hook
# Generated by debian-composer-go

set -e

echo "Running pre-push checks..."

# Run all tests
if command -v go &> /dev/null && [ -f "go.mod" ]; then
    echo "Running tests..."
    go test ./... -v -count=1
fi

# Run linting if golangci-lint is available
if command -v golangci-lint &> /dev/null; then
    echo "Running linter..."
    golangci-lint run
fi

echo "Pre-push checks passed!"
`
}

// FormatHookStatus formats hook status for display
func FormatHookStatus(hooks []GitHook) string {
	var sb strings.Builder

	sb.WriteString("Git Hooks Status:\n")
	sb.WriteString("─────────────────\n")

	for _, hook := range hooks {
		status := "disabled"
		if hook.Enabled {
			status = "enabled"
		}
		sb.WriteString(fmt.Sprintf("  %-20s %s\n", hook.Type, status))
	}

	return sb.String()
}
